"""Address table

Revision ID: f431f181d6fe
Revises: 
Create Date: 2019-01-30 14:38:03.069897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f431f181d6fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ep_adr_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_ep_adr_id'), 'address', ['ep_adr_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_ep_adr_id'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
